In [2]:
list1=[11,23.22,"hello",11]
print(list1)

[11, 23.22, 'hello', 11]


In [28]:
list1=[54,3,67,89,12,76]
ele=int(input("enter element to find "))
for i in range(0,len(list1)):
    if ele in list1:
        print(ele, "found")
        break;


enter element to find 3
3 found


In [18]:
list1=[54,3,67,89,12,76]
print(len(list1))

6


In [32]:
list1=[]
n=int(input("Enter number of list item:"))
for i in range(0,n):
    ele=int(input("Enter element :" + str(i+1)+" "))
    list1.append(ele)
print(list1)
print(len(list1))

Enter number of list item:5
Enter element :1 12
Enter element :2 432
Enter element :3 534
Enter element :4 565
Enter element :5 2321
[12, 432, 534, 565, 2321]
5


In [3]:
for i in range(1,6):
    print(i**2)

1
4
9
16
25


In [10]:
list1=[1,2,3,4,5,6,7]
n=len(list1)
for i in range(n,0,-1):
    print(i)

7
6
5
4
3
2
1


In [14]:
list1=[43,11,22,76,45,67,9]
rev_sort=sorted(list1,reverse=True)
print(rev_sort)  

[76, 67, 45, 43, 22, 11, 9]


In [16]:
list1=[1,2,3,4]
list2=[4,3,2,1]
set1=set(list1)
set2=set(list2)
if set1==set2:
    print("Equal")
else:
    print("Not equal")

equal


In [24]:
list1=[11,22,33,4,5,6,9,7]
list1.remove(33)
list1.pop()
# list1.clear()
print(list1)


[11, 22, 4, 5, 6, 9]


In [26]:
import numpy as np
a=[1,2,3,4,5,6]
x=np.asfarray(a)
print(x)

[1. 2. 3. 4. 5. 6.]


In [33]:
import numpy as np
list1=[11,22,33,44,55,66,77]
tuple1=(1,2,3,4,5,5,6)
print(type(list1))
print(type(tuple1))

arr1=np.array(list1)
arr2=np.array(tuple1)

print(arr1)
print(arr2)




<class 'list'>
<class 'tuple'>
[11 22 33 44 55 66 77]
[1 2 3 4 5 5 6]


In [34]:
import numpy as np
list1=[11,22,33,44,55,66,77]
tuple1=(1,2,3,4,5,5,6)
print(type(list1))
print(type(tuple1))

arr1=np.asarray(list1)
arr2=np.asarray(tuple1)

print(arr1)
print(arr2)

<class 'list'>
<class 'tuple'>
[11 22 33 44 55 66 77]
[1 2 3 4 5 5 6]


In [ ]:
n = int(input("Enter the number of terms in the Fibonacci series: "))
f1=0
f2=1
f3=0

for i in range(n):
    print(f1)
    f3=f1+f2
    f1=f2
    f2=f3
    

In [ ]:
l1=[1,2,53,4,5,6]
print(l1.sort())

In [23]:
num1=int(input("enter a :"))
num2=int(input("enter 2:"))
a=num1
b=num2
while b:
    
    a,b=b,a%b
lcm=(num1*num2)//a
print(lcm)



enter a :3
enter 2:16
48
